### PR TITLE
squared psl rules

### PR DESCRIPTION
**Pull request by dickensc**

### CODE REVIEW

**Comment by eriq-augustine** [comment]
Why?

**Comment by dickensc** [comment]
Hyper system used quadratic rules and the examples for lastfm and yelp were linear form. 
Linear pushes predicates to extreme, i.e. 0 or 1, values, while is this applications we are interested in seeing values between [0, 1].

**Comment by eriq-augustine** [comment]
I see mostly unsquared rules:
 - https://github.com/pkouki/recsys2015/blob/master/src/main/java/edu/ucsc/cs/model/LastfmPerceptronWeightLearning.groovy#L120
 - https://github.com/pkouki/recsys2015/blob/master/src/main/java/edu/ucsc/cs/model/YelpPerceptronWeightLearning.groovy#L118

> Linear pushes predicates to extreme, i.e. 0 or 1, values, while is this applications we are interested in seeing values between [0, 1].

This is not fully true (both clauses).
Also, remember who you are talking to.
I understand what squaring a rule does, I was asking you why you wanted to make the change.

**Comment by dickensc** [comment]
I was using https://github.com/pkouki/iui19 as a reference for the most up to date version of the model. Should we use the recsys2015 version?

**Comment by eriq-augustine** [comment]
The README of each psl-example describes where the data and model is from.
These READMEs cite kouki-recsys15:
https://github.com/linqs/psl-examples/blob/master/lastfm/README.md

A big part of the hyper hackathon is to create an updated hyper model.
The model can eventually live in psl-examples, but the existing models here are archived (not live) versions of hyper.

The short answer is:
kouki-recsys15 should be used, the updated hyper model should be developed elsewhere and eventually moved into psl-examples.

**Comment by dickensc** [comment]
Okay understood. Sorry if I offended you about my why explanation, I didn't mean to. Thank you for the feedback.

**Pull request closed without merging**
